### ISSUE TITLE
ppo_lag does not work well in ray1.2

### ISSUE THREAD

**Issue by feidieufo** [decisionforce/EGPO#3]
I found that ppo_lag has errors in ray1.2 but work well in ray1.0

in ray1.2 has two errors:
1.https://github.com/decisionforce/EGPO/blob/main/egpo_utils/ppo_lag/ppo_lag.py#L92
key "cost" error

2.https://github.com/decisionforce/EGPO/blob/main/egpo_utils/ppo_lag/ppo_lag.py#L389
key "cost" error

**Comment by pengzhenghao** [comment]
Hi @feidieufo ,

This is an known issue since we developed EGPO based on ray 1.0, as shown in `setup.py`:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/22206995/139625965-a6644f75-9b45-4dcf-87c5-c950c57727f5.png">


We only update to ray 1.2 for BC and CQL, as said in `README.md`:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/22206995/139625990-57e8a83a-6006-4cb2-922c-aca0568ea604.png">

Ray is evolving so frequently, thus it's hard for us to keep our code on track. Thanks a lot for trying our code!
